# Generated by Django 6.1.1 on 2026-10-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('price', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'ordering': ['opis_id'],
            },
        ),
    ]
